projects:
  brukerapi:
    schema: app/src/main/resources/bruker.graphql
    documents: app/src/**/bruker/**/*.kt
  produsentapi:
    schema: app/src/main/resources/produsent.graphql
    documents:
      - app/src/**/produsent/**/*.kt
      - test-produsent/**/*
      - http/produsent/*.http
  produsentapidevgcp:
    schema:
      - app/src/main/resources/produsent.graphql
      - https://ag-notifikasjon-produsent-api.intern.dev.nav.no/api/graphql:
          headers:
            user-agent: JS GraphQL
            authorization: Bearer ${auth_token}
