projects:
  brukerapi:
    schema: ./src/main/resources/bruker.graphql
    documents: ./src/**/bruker/**/*.kt
  produsentapi:
    schema: ./src/main/resources/produsent.graphql
    documents: ./src/**/produsent/**/*.kt
  produsentapidevgcp:
    schema:
      - https://ag-notifikasjon-produsent-api.intern.dev.nav.no/api/graphql:
          headers:
            user-agent: JS GraphQL
            authorization: Bearer ${fakedings_token}
