apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: notifikasjon-ekstern-varsling
  namespace: fager
  labels:
    team: fager
spec:
  image: {{image}}
  liveness:
    path: /internal/alive
  readiness:
    path: /internal/ready
  replicas:
    min: 1
    max: 2
  prometheus:
    enabled: true
    path: /internal/metrics
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: altinn-varsel-firewall
      external:
        - host: tt02.altinn.no
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        tier: db-f1-micro
        diskAutoresize: true
        highAvailability: false
        databases:
          - name: ekstern-varsling-model
            envVarPrefix: DB
  envFrom:
    - secret: altinn-basic-ws