apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: notifikasjon-kafka-reaper
  namespace: fager
  labels:
    team: fager
spec:
  image: {{image}}
  liveness:
    path: /internal/alive
  readiness:
    path: /internal/ready
  replicas:
    min: 1
    max: 2
  prometheus:
    enabled: true
    path: /internal/metrics
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        tier: db-custom-1-3840
        diskSize: 20
        diskAutoresize: true
        highAvailability: false
        databases:
          - name: kafka-reaper-model
            envVarPrefix: DB
  env:
    - name: JAVA_OPTS
      value: -Dio.ktor.development=true