apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: notifikasjon-produsent-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
    subteam: msa
spec:
  image: {{image}}
  ingresses:
    - https://arbeidsgiver-notifikasjon-produsent-api.dev.nav.no/
  liveness:
    path: /internal/alive
  readiness:
    path: /internal/ready
  prometheus:
    enable: true
    path: /internal/metrics
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no