apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: notifikasjon-produsent-api
  namespace: fager
  labels:
    team: fager
spec:
  image: {{image}}
  ingresses:
    - https://ag-notifikasjon-produsent-api.dev.nav.no/
  liveness:
    path: /internal/alive
  readiness:
    path: /internal/ready
  replicas:
    min: 2
    max: 8
  prometheus:
    enabled: true
    path: /internal/metrics
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        tier: db-custom-1-3840
        diskSize: 20
        diskAutoresize: true
        highAvailability: false
        databases:
          - name: produsent-model
            envVarPrefix: DB
  accessPolicy:
    outbound:
      external:
        - host: fakedings.dev-gcp.nais.io
        - host: arbeidsgiver.dev.nav.no
    inbound:
      rules:
        - application: notifikasjon-test-produsent
  env:
    - name: JAVA_OPTS
      value: -Dio.ktor.development=true
  envFrom:
    - secret: notifikasjon-produsent-api-secrets
