title: Notifikasjoner for arbeidsgivere
description: Dokumentasjon for å produsere notifikasjoner rettet mot arbeidsgivere.
url: "https://navikt.github.io"
baseurl: "/arbeidsgiver-notifikasjon-produsent-api"

theme: minima

markdown: CommonMarkGhPages