name: deploy dev auto
on:
  workflow_run:
    workflows: [build]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo action: ${{ github.action }}
          echo actor: ${{ github.actor }}
          echo event:
          cat <<EOF
          ${{ toJSON(github.event) }}
          EOF
