name: deploy kafka topic

on:
  push:
    branches: ['main']
    paths: ['config/nais-kafka-topic.yaml', 'config/nais-kafka-topic-ekstern-varsling-status.yaml']
  workflow_dispatch:

jobs:
  deploy-kafka:
    name: Deploy kafka
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: config/nais-kafka-topic.yaml
          PRINT_PAYLOAD: true
          VAR: pool=nav-dev

      - uses: nais/deploy/actions/deploy@v1
        if: github.ref == 'refs/heads/main'
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: config/nais-kafka-topic.yaml
          PRINT_PAYLOAD: true
          VAR: pool=nav-prod

      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: config/nais-kafka-topic-ekstern-varsling-status.yaml
          PRINT_PAYLOAD: true
          VAR: pool=nav-dev

      - uses: nais/deploy/actions/deploy@v1
        if: github.ref == 'refs/heads/main'
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: config/nais-kafka-topic-ekstern-varsling-status.yaml
          PRINT_PAYLOAD: true
          VAR: pool=nav-prod
