name: "Platform: deploy replay-validator prod"
on:
  workflow_dispatch:

jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nais/login@v0
        id: login
        with:
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          team: fager
      - uses: nais/deploy/actions/deploy@v2
        name: "prod-gcp: deploy replay-validator"
        env:
          VAR: image=${{ steps.login.outputs.registry }}/arbeidsgiver-notifikasjon-produsent-api:${{ github.sha }}
          REF: ${{ github.sha }}
          CLUSTER: prod-gcp
          RESOURCE: app/nais/prod-gcp-replay-validator.yaml