name: test
on:
  push:
    paths: ["app/**/*"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v1
      - run: PGPASSWORD=postgres psql -U postgres -p postgres -h postgres -f ./local-db-init.sql
      - uses: actions/setup-java@v1
        with:
          java-version: '15.x'
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - run: mvn -B test
        working-directory: app
